added some effects on hyperlinks
singul4ri7y/gsoc2024 pull request #1
Opened 2024-12-28 13:23 UTC by HeheAnanya

Hi, I have added some effects on text containing hyperlinks. Like on hovering over the text the text font size will increase and also the color will also change (The choise of color has been chosen by keeping the white theme too in mind).

2024-12-28 14:54 UTC, singul4ri7y requested changes
Thanks for the PR, Ananya.

Though I was not planning for any PR in this repo, hence no CD is prepared for PRs. Can you please host your version of the page and provide me the link? If it's good enough, I will accept the PR. But at first look, I don't think 

Cheers,
Asif

2024-12-28 14:54 UTC, singul4ri7y commented on styles.css
> +}git
I presume the "git" keyword here is unintentional?

2024-12-28 14:54 UTC, singul4ri7y commented on styles.css
> +    font-size: 1.2rem;
I think different color would be nice to have for different theme. Try using `body.dark` and `body.light` directives before `.effect` and `#effect` to set colors for different themes. Try choosing some aesthetic colors, nothing too eye-blinding such as red ;).

2024-12-29 08:03 UTC, HeheAnanya commented
Hi Asif,

Apologies if I caught you by surprise! I’ve made the required changes as per your feedback and have also deployed the work. Here’s the link to the page: https://heheananya.github.io/try_gsoc/ .

Please take a look, and let me know if anything further needs to be adjusted.

Cheers,
Ananya

2024-12-29 15:18 UTC, singul4ri7y commented
Hey Ananya, thanks for hosting and sending the link over.

I think the color and font change on hover does not go well with overall look and feel of the page! I think it would be better if you:
 - Get rid of the font changing on hover effect.
 - Add transition effects with the `transition` property (you can look it over the internet).
 - Add underlining effect (with transition) to indicate they are links.
 - And finally choose colors conforming with overall look and feel. One hint would be [maybe you might already did that], to use any sort of AI tools (In this case, ChatGPT would suffice) and probe all the available colors conforming the fg color (text color) and the bg color for both dark and light themes. You can begin by providing seeds and keyword like the bg and fg color of the page of both dark and light theme scenarios, "aesthetic", "warm", "for foreground color" etc.

2024-12-30 08:00 UTC, HeheAnanya commented
Hi Asif,
I've made the necessary changes to align better with the overall look and feel of the page.
Thanks for your suggestions and tips, and I hope the changes work better for you now!

2024-12-30 12:28 UTC, singul4ri7y commented
Hey Ananya, I think the page has not been deployed yet, the changes you made is not affecting the hosted page.

By the look on your profile, you are using another repository `try_gsoc` for the page host. You can enable GitHub hosting on the forked repository you commit your changes to, in this way you won't have to worry about manual deployment.

2024-12-30 12:47 UTC, HeheAnanya commented
Updated

2024-12-30 13:51 UTC, singul4ri7y requested changes
The color and everything looks good! Just some minor nits.

2024-12-30 13:51 UTC, singul4ri7y commented on index.html
> +                <p>Ahh, who could&#39;ve thought? I spent my entire summer coding away as part of <a href="summerofcode.withgoogle.com" class="effect">Google Summer of Code</a>! Feels like the summer
Here I have encountered a bug (ouch)!

I should have put `https://` in front of the link. Now I can fix this, but after I make my commit you would have to rebase your repo which might make things complicated more than it needs to be. You may want to fix this (as it's an easy fix) if you don't want to rebase.

2024-12-30 13:51 UTC, singul4ri7y commented on styles.css
> +    text-decoration: underline;
I have looked into the hosted site and it seems like the transition is happening instantaneously (or it's not working properly). You also might want to use `all` as transition property, as the transition in color might also look good.

2025-11-15 05:18 UTC, PredictiveManish commented on index.html
> +                <p>Konnichiwa, I&#39;m Syed Naimul Hasan Asif (alias SD Asif Hossein), an Electrical Engineering undergrade student from Bangladesh who is passionate about low-level programming, prog
undergrade?? it should be either undergraduate or undergrad.

2025-11-15 06:49 UTC, singul4ri7y commented
This PR is working on very small changes and not doing very well. Not to mention, it's creating a lotta noise. Closing this PR.

2025-11-15 06:49 UTC, closed without merging